export  { default as cancelImage }  from './images/cancel.svg';
export { default as chatImage} from './images/chat.svg';
export { default as bellImage} from './images/bell.svg';
export { default as checkImage} from './images/check.svg';
export { default as exploreImage} from './images/explore.svg';
export { default as  expandImage} from './images/expand.svg';
export { default as editImage } from './images/edit-btn.svg';
export { default as logoImage} from './images/logo.svg';
export { default as clockImage} from './images/clock.svg';
export { default as searchImage} from './images/search.svg';
export { default as notifyImage }from './images/notify.svg';
export { default as addImage} from './images/add.svg';
export { default as settingImage} from './images/setting.svg';
export { default as deleteImage} from './images/delete.svg';
export { default as fbImage} from './images/fb.svg';
export { default as twitterImage} from './images/twitter.svg';
export { default as googleImage} from './images/google.svg';
export { default as sendImage} from './images/sendbtn.svg';
export { default as dropMenuImage} from './images/drop-menu.svg';
export { default as userImage} from './images/user.svg' ;
export { default as medicalImage} from './images/medical.svg';
export { default as dropWhiteMenu} from './images/drop-menu-white.svg';
export {default as forgotWeb} from './images/forgot.webp';
export {default as cancleWhiteImage} from './images/cancel-white.svg';
export {default as dustbinImage} from './images/dustbin.svg'
export {default as plusBlue} from './images/plus-blue.svg'
export {default as canceldrop} from './images/canceldrop.svg';
export {default as blueNotification} from './images/notification_blue.svg';
export { default as documentImage} from './images/document.svg';
export { default as checkInImage} from './images/checkin.svg';